site_name: WV2M Installation Manual

theme:
  name: rtd-dropdown

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Quick Installation: quick_installation.md
  - Components: components.md
  - Physical Mounting: physical_mounting.md