site_name: WV2M Installation Manual

theme:
  name: material
  features:
      - navigation.sections
      - navigation.expand
      - navigation.top
      - search.suggest
      - search.highlight
      - content.code.copy 

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Quick Installation: quick_installation.md
  - Components: components.md
  - Physical Mounting: physical_mounting.md
  - Pairing WV2M with the Wireless M Console: pairing.md
  - Configuring the WV2M: configuring.md
  - Manual Override: manual_override.md
  - Replacing Battery: replacing_battery.md
  - LED Indications: led_indications.md
  - Resetting: resetting.md
  - Upgrading Firmware: upgrading_firmware.md
  - Technical Specifications: tech_spec.md

markdown_extensions:
 - admonition 
 - attr_list
 - pymdownx.details
 - pymdownx.superfences